In [3]:
import pandas as pd
Artists = pd.read_csv('./Artists.csv')

In [4]:
Artists.head

<bound method NDFrame.head of        ConstituentID                           DisplayName  \
0                  1                        Robert Arneson
1                  2                        Doroteo Arnaiz
2                  3                           Bill Arnold
3                  4                       Charles Arnoldi
4                  5                           Per Arnoldi
5                  6                         Danilo Aroldi
6                  7                             Bill Aron
7                  9                         David Aronson
8                 10                         Irene Aronson
9                 11                       Jean (Hans) Arp
10                12                            Jüri Arrak
11                13                   J. Arrelano Fischer
12                15                         Folke Arstrom
13                16                     Cristobal Arteche
14                18                                 Artko
15                19                   Richard Artschwager
16                21                            Ruth Asawa
17                22                      Isidora Aschheim
18                23                 Charles Robert Ashbee
19                24                       Donald Ashcraft
20                25                            E. M. Ashe
21                26                           Göran Åslin
22                27                   Erik Gunnar Asplund
23                28                        Geneviève Asse
24                30                           Sergio Asti
25                31                          Dana Atchley
26                32                        Atelier Eggers
27                33                                A.A.P.
28                34                           Alvar Aalto
29                35                            Aino Aalto
...              ...                                   ...
15787          74998                          Leandro Feal
15788          75011                         Nelly Richard
15789          75013                    Tiago Mata Machado
15790          75015                            Sanlé Sory
15791          75017                                Myrbor
15792          75021                    The Crawford Shops
15793          75037               Margaret Hoening French
15794          75045                          John Jesurun
15795          75046                      Gastón Solnicki
15796          75051                           Ela Troyano
15797          75052                            Uzi Parnes
15798          75054                    Peter von Ziegesar
15799          75060                        Susan Tremblay
15800          75076                         Zoltán Réczey
15801          75080                        Robert Kurilla
15802          75081      DIAB (Dataindustrier AB), Sweden
15803          75090                           Sky Hopinka
15804          75093                        Marta Popivoda
15805          75094                          Joel Winston
15806          75096                          Nathan Juran
15807          75097                        Becky Johnston
15808          75098                      Rachid Kerdouche
15809          75099                        Alison Maclean
15810          75100                        S. Jay Kaufman
15811          75105                           Greg Paxton
15812          75110                    Jordan Grabulovski
15813          75133  Zeiss-Werk, Jena, East Germany (DDR)
15814          75256                             Hans Berg
15815          75301                           Mario Meier
15816          75318                          Hermann Heid

                                      ArtistBio Nationality  Gender  \
0                           American, 1930–1992    American    Male
1                            Spanish, born 1936     Spanish    Male
2                           American, born 1941    American    Male
3                           American, born 1946    American    Male
4                             Danish, born 1941      Danish    Male
5                            Italian, born 1925     Italian    Male
6                           American, born 1941    American    Male
7                 American, born Lithuania 1923    American    Male
8                   American, born Germany 1918    American  Female
9      French, born Germany (Alsace). 1886–1966      French    Male
10                          Estonian, born 1936    Estonian    Male
11                           Mexican, 1911–1995     Mexican    Male
12                           Swedish, 1907–1997     Swedish    Male
13                           Spanish, 1900–1964     Spanish    Male
14                                          NaN         NaN     NaN
15                          American, 1923–2013    American    Male
16                          American, 1926–2013    American  Female
17                                      Israeli     Israeli  Female
18                           British, 1863–1942     British    Male
19                          American, born 1927    American    Male
20                          American, 1867–1941    American    Male
21                           Swedish, born 1940     Swedish     NaN
22                           Swedish, 1885–1940     Swedish    Male
23                            French, born 1923      French  Female
24                           Italian, born 1926     Italian    Male
25                          American, 1941–2000    American  Female
26                                       French      French     NaN
27                                     American    American     NaN
28                           Finnish, 1898–1976     Finnish    Male
29                           Finnish, 1894–1949     Finnish  Female
...                                         ...         ...     ...
15787                          Cuban, born 1986       Cuban    Male
15788           Chilean, born in France in 1948     Chilean  Female
15789                      Brazilian, born 1973   Brazilian     NaN
15790                      Burkinabe, born 1943   Burkinabe    Male
15791            French and Algerian, 1922–1936      French     NaN
15792                                  American    American     NaN
15793                       American, 1906–1998    American  Female
15794                       American, born 1951    American    Male
15795                      Argentine, born 1978   Argentine    Male
15796                                  American    American  Female
15797                       American, born 1954    American    Male
15798                       American, born 1952    American    Male
15799                       American, born 1957    American  Female
15800                      Hungarian, born 1969   Hungarian    Male
15801                       American, born 1958    American    Male
15802                                 est. 1970         NaN     NaN
15803                       American, born 1984    American    Male
15804                        Serbian, born 1982     Serbian  Female
15805                       American, born 1954    American    Male
15806                       Romanian, 1907–2002    Romanian    Male
15807                       American, born 1956    American  Female
15808                         French, born 1949      French    Male
15809                       Canadian, born 1958    Canadian  Female
15810                       American, 1886–1957    American    Male
15811                       American, born 1962    American    Male
15812                     Macedonian, 1925–1986  Macedonian    Male
15813                                       NaN         NaN     NaN
15814                        Swedish, born 1978     Swedish     NaN
15815                          Swiss, born 1938       Swiss    Male
15816                       Austrian, 1834–1891    Austrian    Male

       BeginDate  EndDate   Wiki QID         ULAN
0           1930     1992        NaN          NaN
1           1936        0        NaN          NaN
2           1941        0        NaN          NaN
3           1946        0   Q1063584  500027998.0
4           1941        0        NaN          NaN
5           1925        0        NaN          NaN
6           1941        0        NaN          NaN
7           1923        0   Q5230870  500003363.0
8           1918        0  Q19748568  500042413.0
9           1886     1966    Q153739  500031000.0
10          1936        0        NaN          NaN
11          1911     1995        NaN          NaN
12          1907     1997        NaN          NaN
13          1900     1964        NaN          NaN
14             0        0        NaN          NaN
15          1923     2013    Q568262  500114981.0
16          1926     2013   Q7382874  500077806.0
17             0        0        NaN          NaN
18          1863     1942    Q614071  500030367.0
19          1927        0        NaN          NaN
20          1867     1941        NaN          NaN
21          1940        0        NaN          NaN
22          1885     1940    Q312070  500011232.0
23          1923        0   Q1978192  500025324.0
24          1926        0        NaN          NaN
25          1941     2000        NaN          NaN
26             0        0        NaN          NaN
27             0        0        NaN          NaN
28          1898     1976     Q82840  500002617.0
29          1894     1949    Q273511  500024110.0
...          ...      ...        ...          ...
15787       1986        0        NaN          NaN
15788       1948        0        NaN          NaN
15789       1973        0        NaN          NaN
15790       1943        0        NaN          NaN
15791       1922     1936        NaN          NaN
15792          0        0        NaN          NaN
15793       1906     1998        NaN          NaN
15794       1951        0        NaN          NaN
15795       1978        0        NaN          NaN
15796          0        0        NaN          NaN
15797       1954        0        NaN          NaN
15798       1952        0        NaN          NaN
15799       1957        0        NaN          NaN
15800       1969        0        NaN          NaN
15801       1958        0        NaN          NaN
15802       1970        0        NaN          NaN
15803       1984        0        NaN          NaN
15804       1982        0        NaN          NaN
15805       1954        0        NaN          NaN
15806       1907     2002        NaN          NaN
15807       1956        0        NaN          NaN
15808       1949        0        NaN          NaN
15809       1958        0        NaN          NaN
15810       1886     1957        NaN          NaN
15811       1962        0        NaN          NaN
15812       1925     1986        NaN          NaN
15813          0        0        NaN          NaN
15814       1978        0        NaN          NaN
15815       1938        0        NaN          NaN
15816       1834     1891        NaN          NaN

[15817 rows x 9 columns]>

In [5]:
Artists.columns

Index(['ConstituentID', 'DisplayName', 'ArtistBio', 'Nationality', 'Gender',
       'BeginDate', 'EndDate', 'Wiki QID', 'ULAN'],
      dtype='object')